# Generated by Django 3.1.14 on 2023-06-03 10:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='pokemons')),
                ('description', models.TextField(blank=True, null=True)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('title_jp', models.CharField(blank=True, max_length=200)),
                ('previous_evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_evolution', to='pokemon_entities.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('appeared_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disappeared_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.IntegerField(null=True)),
                ('health', models.IntegerField(null=True)),
                ('strength', models.IntegerField(null=True)),
                ('defence', models.IntegerField(null=True)),
                ('stamina', models.IntegerField(null=True)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon')),
            ],
        ),
    ]
